required = ["github.com/onsi/ginkgo/ginkgo"]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry-incubator/bosh-load-tests"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
