---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main

inputs:
- name: bosh-fuzz-tests
- name: bosh-src

run:
  path: bosh-fuzz-tests/ci/tasks/test.sh

params:
  RUBY_VERSION: 2.3
  SEED: ~
  BOSH_SRC_PATH: bosh-src/src
